### ISSUE TITLE
Some MySql function added

### ISSUE THREAD

**Issue by muka** [creof/doctrine2-spatial#11]
Hi,
on https://github.com/muka/doctrine2-spatial/commit/4844d597176ef69ac4fdef9098022e0d400ceeff

I've added some MySql specific function. Please consider if they can be useful to the project.

Thank your.
Regards

**Comment by sadortun** [comment]
Can you rebase on master and submit a PR ? 

Thanks,
Samuel

**Comment by sadortun** [comment]
Merged into develop branch
