### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by sadortun** [creof/doctrine2-spatial#114]
Hi @djlambert  @ddproxy,

There is 4 branches that i am not sure if we should either merge, or delete and re-submit a PR if needed from a fork when the work will be completed:

- MySQL-srid
- fix-backport
- php55-fixes
- sandbox

Can you have a look ?

**Comment by ddproxy** [comment]
Looks like everything is merged, not working or not worth touching other than sandbox - which is @djlambert's domain.

Double check the fix-backport, as it's a little interesting, php55-fixes has already been merged and the mysql-srid seems moot.

I support killing everything off other than sandbox, until @djlambert takes it back into his local dev?

**Comment by djlambert** [comment]
I agree they can all go. I have a local copy of sandbox. I think everything in fix-backport I re-fixed now in master while I was monkeying with the tests.

**Comment by ddproxy** [comment]
Removed, closing ticket
