### ISSUE TITLE
PostGis raster support

### ISSUE THREAD

**Issue by rabbl** [creof/doctrine2-spatial#134]
It would be nice to add the postgis-type raster to the supported geo-types.

**Comment by rabbl** [comment]
I'll try this, if you agree with this issue.

**Comment by ddproxy** [comment]
That would be fun but I haven't a clue where to start with that. We could obviously just implement 
methods from http://postgis.net/docs/manual-2.1/RT_reference.html but raster object support is not a short-term goal.

With that in mind, you can test several of these by defining your own methods then porting them into D2S (with tests).

**Comment by rabbl** [comment]
I'm still not very familiar with DBAL and new in the topic of spatial data and postgis.
Also I'm still struggling with understanding the code well enough to participate in a productive way.
My idea is to implement raster as another SpatialType that is not GeographyType nor GeometryType.
Until now I solved the issue with plain sql. But it's not so nice.
I could implement the main functions to add rasters, like:

- st_makeemptyraster
- st_addband
- st_setvalues

and solve it with dql. 
That could be a first step, what du you think?

**Comment by ddproxy** [comment]
I think that's a great start. We'll need to (hypothetically) add support for raster objects in PHP to transition further.

**Comment by rabbl** [comment]
To implement the raster functionality the BasicEntityPersister of Doctrine has to be overridden. At the moment Doctrine isn't providing this feature.

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/limitations-and-known-issues.html#custom-persisters

So, i'll close this issue until Doctrine offers this.
