### ISSUE TITLE
multiPolygon is saved as polygon when saving to database

### ISSUE THREAD

**Issue by collmomo** [creof/doctrine2-spatial#135]
#CrEOF\Spatial\PHP\Types\AbstractMultiPolygon

     /**
     * @return string
     */
    public function getType()
    {
        return self::POLYGON;
    }`

I don't know if thats wanted but this specific portion of code makes believe your wkt parser that this is a polygon and as a consequence the wkt is saved as such `'POLYGON (.....)' `when it should be `'MULTIPOLYGON(....)'.` I tried changing it to `self::MULTIPOLYGON`, but then it tells me the parser doesn't exist which leads me to believe this was intended.

**Comment by sadortun** [comment]
Hi @collmomo,

Good catch! We will have a look!

**Comment by collmomo** [comment]
I strongly suggest using GeoPHP, the json to wkt is perfect for all different possibilities of geometries: https://geophp.net. In fact, I'm just gonna rewrite the types and change the convertToSQL functions using GeoPhp ones. Given I have an array, I'll just json_encode it. Plus you can access to many practical functions if you create a geophp object inside each geometry type.

**Comment by djlambert** [comment]
What library version are you referencing in your composer.json? I may be missing something but ```CrEOF\Spatial\PHP\Types\AbstractMultiPolygon::getType()``` returns ```self::MULTIPOLYGON``` 
https://github.com/creof/doctrine2-spatial/blob/master/lib/CrEOF/Spatial/PHP/Types/AbstractMultiPolygon.php#L108

**Comment by djlambert** [comment]
Adding support for the use of other geometry objects (including GeoPHP) is in the works. I'd like to avoid introducing unnecessary external dependencies into the library.

**Comment by sadortun** [comment]
I think @collmomo  was refering to https://github.com/creof/doctrine2-spatial/blob/bfd98cb89f24230e6d2d064d5431fd20e0cabf10/lib/CrEOF/Spatial/PHP/Types/AbstractPolygon.php#L108

@collmomo Did you had an problem with the polygons or you only noticed this in the code ? 

To recap :

```php
AbstractPolygon::getType()
    {
        return self::POLYGON;
    }
```

```php
AbstractMultiPolygon::getType()
    {
        return self::MULTIPOLYGON;
    }
```

I dont think there is an issue there.

**Comment by collmomo** [comment]
Sorry, it was an old version of the library. I just ran composer update and that Issue disappeared. it was 
AbstractMultiPolygon::getType()
    {
        return self:POLYGON;
    }

**Comment by sadortun** [comment]
Ok, thanks for the update.
