### ISSUE TITLE
Coveralls / CodeClimate hooks not running

### ISSUE THREAD

**Issue by sadortun** [creof/doctrine2-spatial#142]

**Comment by djlambert** [comment]
Probably need to add the develop branch. I'll take a look.

**Comment by sadortun** [comment]
Coveralls was on Dec 25
Code Climate was on Feb 16.

**Comment by djlambert** [comment]
:confounded: Code Climate:

Default branch only:
We only support test coverage for your default branch. Be sure to check out this branch before running your tests

**Comment by sadortun** [comment]
https://travis-ci.org/creof/doctrine2-spatial/jobs/121185738#L686
```
0.14s$ ./vendor/bin/coveralls -v --exclude-no-stmt
                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "src_dir" under "coveralls"                                
```

**Comment by djlambert** [comment]
#143 should have triggered Code Climate. This week is all about things breaking.

**Comment by sadortun** [comment]
I added the webhook, and seems to work

![image](https://cloud.githubusercontent.com/assets/794449/14336805/a7fdd368-fc35-11e5-9df5-047fe15c4216.png)

**Comment by sadortun** [comment]
Yep it's working !

![image](https://cloud.githubusercontent.com/assets/794449/14336816/e97a650e-fc35-11e5-9dea-3feee8f653c1.png)
