### ISSUE TITLE
Mixup of latitude/logitude vs. x/y in class AbstractPoint

### ISSUE THREAD

**Issue by fogs** [creof/doctrine2-spatial#16]
Actually implemented
 * setLatitude() calls setY() 
 * getLatitude() calls getY() 
 * setLongitude calls setX()
 * getLongitude calls getX()

Instead X should represent the latitude, Y the longitude. This is even how it is stated in the first lines of lib/CrEOF/Spatial/PHP/Types/AbstractPoint.php:

```php
/**
 * @var float $latitude
 */
    protected $x;

/**
 * @var float $longitude
 */
    protected $y;
```

**Comment by djlambert** [comment]
Closing this issue. The PHP objects classes are being moved into the creof/geo library and interfaces added allowing the use of custom objects if desired. Compatibility with the existing implementation may require an additional "compat" library to bridge the gap, the goal being limiting any code changes to simply including the additional package dependencies.
