### ISSUE TITLE
Package is not compatible with current versions of Doctrine

### ISSUE THREAD

**Issue by lupinitylabs** [creof/doctrine2-spatial#224]
Several methods of the `AbstractSpatialType` are incompatible with current Doctrine versions, because they are missing parameter and return types, or have different parameter names. This leads to fatal errors like

`Declaration of CrEOF\Spatial\DBAL\Types\AbstractSpatialType::convertToPHPValue($value, Doctrine\DBAL\Platforms\AbstractPlatform $platform) must be compatible with Doctrine\DBAL\Types\Type::convertToPHPValue(mixed $value, Doctrine\DBAL\Platforms\AbstractPlatform $platform): mixed`

My main question here is: since this package has not been updated in over 6 years, is it abandoned?

I have created a fork fixing this, and am willing to make a PR, but only if there's any interest by the maintainers to actually merge and publish it. Please consider marking this repository as abandoned so the community knows what to expect.

**Comment by samwilson** [comment]
Not sure about the status of this repo, but I've switched to the [longitude-one/doctrine-spatial](https://packagist.org/packages/longitude-one/doctrine-spatial) package.

**Comment by lupinitylabs** [comment]
Yes, me too in the meantime 😄 
Thanks for the notice anyways!

I thought there's probably a reason why it was called doctrone2-spatial to begin with.
