### ISSUE TITLE
I pulled together some changes that seemed good a while back, here they are

### ISSUE THREAD

**Issue by mythril** [creof/doctrine2-spatial#24]
[Changes](https://github.com/mythril/doctrine2-spatial/compare/djlambert:master...master)

I didn't offer them as a pull request because it includes some composer package info that I changed, so I could use the improvements and still treat it like an external package.

**Comment by sadortun** [comment]
Hi @mythril,

Can you rebase on master and submit a PR. We will review your changes and ignore the composer package changes.

Thanks,
Samuel
