### ISSUE TITLE
Packagist Versioning

### ISSUE THREAD

**Issue by HurricaneHarry** [creof/doctrine2-spatial#28]
When are you planning to do a x.y.z numerical versions of the package?

It'd be nice to have the ability to "djlambert/doctrine2-spatial" : "0.1.*"  so I can have the updates over time instead changing the version names for each revision.

I'd like to do something other than dev-master, preferably.

**Comment by sadortun** [comment]
Tag 0.1 now available !   0.2 will probably come soon :wink:
