### ISSUE TITLE
Support for 'altitude' axis to ensure compatibility with KML

### ISSUE THREAD

**Issue by holtkamp** [creof/doctrine2-spatial#34]
I am currently looking at some homebrew Geometry classes and checking whether they can be replaced by the Doctrine2-spatial classes.

Since I once created these classes to be able to deal with KML files, the 'Point' type also supports the optional 'z' axis, representing the 'altitude'

http://code.google.com/apis/kml/documentation/kmlreference.html#coordinates

Would it be a big problem to add support for this to the Doctrine2-spatial Point type? Or is this a 'no-go-area' ;)? When no problem, I can try to find some time to come up with a PR.

Cheers.

**Comment by ddproxy** [comment]
@holtkamp If you have an update to code that supports altitude/z axis or additional properties (it's weird) I'd be interested in merging.

**Comment by sadortun** [comment]
Would it make sense to have a Point3D class extends the Point class ?

**Comment by holtkamp** [comment]
@ddproxy, no, never went down that road and mostly discarded the altitude information in KML files.

**Comment by djlambert** [comment]
This was actually something I had been investigating implementing once the PHP objects were broken out.
