### ISSUE TITLE
transform point from 2 fields latitude and longitude

### ISSUE THREAD

**Issue by bastienEichenberger** [creof/doctrine2-spatial#42]
Hi,
First of all, thank you for the library its work's great :)
In my form I have 2 fields. I transform those fields in a Point Object in each controller.
Does a best Way exist to have 2 fields (lat + long) in the view and to transform them in a Point object later ?
In advance thanks you for your help.

```
// FormType
$builder->add('lat', 'hidden', array(
    'attr' => array('data-geo' => 'lat')
));
$builder->add('lng', 'hidden', array(
     'attr' => array('data-geo' => 'lng')
));

// Controller
// add location
$lat = $user->getLat();
$lng = $user->getLng();
$point = new Point($lng, $lat, 4326);
$user->setLocation($point);


// user entity
/**
 * @ORM\Entity
 * @ORM\Table(name="tut_user")
 * @UniqueEntity(fields="email", message="fos_user.email.already_used")
 * @UniqueEntity(fields="username", message="fos_user.username.already_used")
 */
class User extends BaseUser {
 /**
 * @ORM\Column(type="point")
*/
protected $location;

public function getLocation() {
        return $this->location;
    }

    public function setLocation(\CrEOF\Spatial\PHP\Types\Geography\Point $point) {
        $this->location = $point;
    }
}
```

**Comment by spackmat** [comment]
This is a very good question, i am wondering this, too.

Is there a best practice to handle doctrine2-spatial's geodata in forms? How do others deal with it?

**Comment by ddproxy** [comment]
@spackmat @bastienEichenberger Use Doctrine's preupdate and prepersist events to generate the actual geometry in the entity.

```
    /**
     * @param MyEntity $entity
     */
    protected function pointCheck(MyEntity &$entity)
    {
        if ($entity->hasCoordinates()) {
            // update geometry if it exists as a point or is null
            if ($entity->getGeometry() === null) {
                $point = new Point(0, 0, 4326);
                $point
                    ->setLongitude($entity->getLongitude())
                    ->setLatitude($entity->getLatitude());
                $entity->setGeometry($point);
            } elseif ($entity->getGeometry() instanceof Point) {
                $point = $asset->getGeometry();

                // only update if coordinates have changed
                if ($point->getLatitude() !== $entity->getLatitude()
                    || $point->getLongitude() !== $asset->getLongitude()
                ) {
                    $point->setLatitude($entity->getLatitude());
                    $point->setLongitude($entity->getLongitude());
                    $entity->setGeometry($point);
                }
            }
        }
    }
````

**Comment by spackmat** [comment]
@ddproxy Thank you. In the meantime, I solved it inside the controller, the new/update-action looks like this:

    if (empty($form->get('geoLongitude')->getData())
        || empty($form->get('geoLatitude')->getData())) {
        $facility->setLocation(new Point(0, 0));
    }
    else {
        $facility->setLocation(new Point(
            $form->get('geoLongitude')->getData(),
            $form->get('geoLatitude')->getData(),
            4326
        ));
    }

and the edit-action looks like this:

    $editForm = $this->createEditForm($entity);
    $editForm->get('geoLatitude')->setData($entity->getLocation()->getLatitude());
    $editForm->get('geoLongitude')->setData($entity->getLocation()->getLongitude());

Not the best place for this, but quite functional.

**Comment by ima-tech** [comment]
If anyone were to stumble on this thread when trying to create a form for a point, I was able to do it using this option:

```
'empty_data' => function (FormInterface $form) {
                return new Point($form->get('longitude')->getData(), $form->get('latitude')->getData());
            },
```

with the complete code being:

`class PointType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add("latitude", NumberType::class, [
                "required" => true,
                "mapped" => false,
                "constraints" => [
                    new NotBlank(),
                    new Range([
                        "min" => -90, "minMessage" => "The minimum value of a latitude cannot be lower than -90.",
                        "max" => 90, "maxMessage" => "The maximum value of a latitude cannot be above +90.",
                    ])
                ]
            ])
            ->add("longitude", NumberType::class, [
                "required" => true,
                "mapped" => false,
                "constraints" => [
                    new NotBlank(),
                    new Range([
                        "min" => -180, "minMessage" => "The minimum value of a longitude cannot be lower than -180.",
                        "max" => 180, "maxMessage" => "The maximum value of a longitude cannot be above +180.",
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Point::class,
            'csrf_protection' => false,
            'empty_data' => function (FormInterface $form) {
                return new Point($form->get('longitude')->getData(), $form->get('latitude')->getData());
            },
        ));
    }
}`
