### ISSUE TITLE
Multipolygon classes are missing

### ISSUE THREAD

**Issue by ibedouglas** [creof/doctrine2-spatial#43]
When I attempt to use the multipolygon type for mysql, I get errors because the referenced classes are missing. I made a branch where this issue is fixed, by creating the classes needed. I'd be happy to push the branch, provided permission.

**Comment by holtkamp** [comment]
+1 for support of MultiPolygons, @ibedouglas is your branch still available?

**Comment by holtkamp** [comment]
Aah, here it is: https://github.com/djlambert/doctrine2-spatial/pull/44

**Comment by ddproxy** [comment]
@holtkamp @ibedouglas I'm working on a merge into my fork

**Comment by holtkamp** [comment]
great, it works ok, if I remember correctly there were some awkward
limitations / specific ways on how to iterate over collections, will look
it up in my internal comments...

**Comment by sadortun** [comment]
#104 merged
