### ISSUE TITLE
ST_Simplify function

### ISSUE THREAD

**Issue by pankas87** [creof/doctrine2-spatial#48]
Currently I need the ST_SImplifiy function to work in DQL.

Is it coing anytime soon? I can give you a hand in writing if you point me in the right direction in your codebase

**Comment by edigu** [comment]
IMO #49 covers this.

**Comment by ddproxy** [comment]
@pankas87 ST_Simplify is available in my fork, sorry this took so long to get updated.

**Comment by sadortun** [comment]
PR #49 merged
