### ISSUE TITLE
postgres 8.x compatability

### ISSUE THREAD

**Issue by tvogt** [creof/doctrine2-spatial#5]
Postgres prior to 9.0 does not support type hints for the geometry/geography type, i.e.:

center geometry(POINT) NOT NULL -- fails
while
center geometry NOT NULL -- works

A simple change in PostgreSql.php (line 55) would fix this - but then it is missing for 9.x. I don't know how to test the version or if it is even possible, so I'm just putting this information here for now.

**Comment by sadortun** [comment]
Postgre < 9.0 have reached end of life in July 2014. Is it still an active issue for anyone ?
