### ISSUE TITLE
save Polygon 

### ISSUE THREAD

**Issue by ekittell** [creof/doctrine2-spatial#50]
When I want to save a polygon from string input I'm using this method in my Entity class to parse the string for me.  I believe there are some string parsing methods included with this package, can I use them instead of this code?  How?  Too bad there's no doc explaining this or anything else, I was able to put this code together just by looking at the test files.

    /**
     * Set polygon
     *
     * @param string $polygon
     * @return Area
     */
    public function setPolygon($polygon)
    {
        $points = array();
        foreach(explode(",", $polygon) as $point) {
            $coordinates = explode(" ", $point);
            echo"$coordinates[0], $coordinates[1] <br>";
            $points[] = new Point($coordinates[0], $coordinates[1]);
        }
        $rings = array( new LineString($points));

        $this->polygon = new Polygon($rings);

        return $this;
    }

**Comment by sadortun** [comment]
Hello @ekittell ,

Have a look at the StringParser class and StringParserTest for usage examples. 

```php
        $value    = 'LINESTRING(34.23 -87, 45.3 -92)';
        $parser   = new StringParser($value);
        $expected = array(
            'srid'  => null,
            'type'  => 'LINESTRING',
            'value' => array(
                array(34.23, -87),
                array(45.3, -92)
            )
        );
        $actual = $parser->parse();
        $this->assertEquals($expected, $actual);

```


https://github.com/creof/doctrine2-spatial/blob/be4ee9aeadb7c886caab2c07ab5b1f13c8b9999e/tests/CrEOF/Spatial/Tests/DBAL/Types/StringParserTest.php#L119
