### ISSUE TITLE
Is this project still alive ? 10 PR are waiting....

### ISSUE THREAD

**Issue by collmomo** [creof/doctrine2-spatial#53]

**Comment by edigu** [comment]
+1

**Comment by hpatoio** [comment]
Don't understand why owner of projects like this one do not put them under control of some organization like "Friend of Doctrine", "Friend of PHP" of whatever. Please @djlambert consider this step.

**Comment by dragosprotung** [comment]
+1

**Comment by tvogt** [comment]
Because largely interest is not so very high, only a few people actually care, and begging some project to take your baby is somewhat insulting.

On the other hand, nothing stops you from forking it and giving the fork to FoS etc.

**Comment by artggd** [comment]
+1

**Comment by nsaleh** [comment]
+1

**Comment by sadortun** [comment]
@djlambert  Can you nominate new moderators/admins to the project ? There is many PR waiting that should be tested and merged.

**Comment by amenadiel** [comment]
:+1: I've long switched to my fork in my composer.json, but that spoils the sense of collaborative coding

**Comment by sadortun** [comment]
@amenadiel  I am using @ddproxy fork, he have made quite a lot of progress and clean-ups  (currently 49 commits ahead of this repo)

**Comment by ddproxy** [comment]
I'm working on separating some of this repositories' logic into two projects. I'll continue to support the creof namespace with new and tested code - its just slow going.

The current state of the project isn't as well tested as if like it to be. If you guys have any requests or prs sitting in waiting let me know and I can pull them in.

**Comment by amenadiel** [comment]
Ok @ddproxy I rebased my PR #33 on top of your current master, and made a pull request on your fork
https://github.com/ddproxy/doctrine2-spatial/pull/8

I'm also pointing my composer.json to your packagist version.

**Comment by sadortun** [comment]
After a couple of day of re-organisation, project is indeed alive!  We are working in merging all open PR, and cleaning up the issues. 

Please note that project was re-located to https://github.com/creof/doctrine2-spatial/

**Comment by holtkamp** [comment]
great news, kudos guys!
