### ISSUE TITLE
Moving toward 1.0

### ISSUE THREAD

**Issue by sadortun** [creof/doctrine2-spatial#90]
Hi,

It have been almost a year since the lib is tagged as 0.1, i think it would be the time to get ready to move on to 1.0
- [x] Merge develop into master @sadortun
- [x]  Code coverage @sadortun
- [x] Resolve query parameter SQL generation issue with orm < 2.5 @djlambert
- [x] Merge docs from https://github.com/ddproxy/doctrine2-spatial/commit/0ea00def7183baba7bf5da66358e36dea22d5f8f  @ddproxy 
- [x] Review CHANGELOG for any missing items @djlambert (and anyone else)
- [x] Add test cases to cover the behaviour of GetGeomFromText escaping with doctrine/orm < 2.5.1 and >= 2.5.1

If there is anything else missing, just edit the issue.

**Comment by djlambert** [comment]
I've found the issue with the tests, and it's actually with parameter handling. I'll explain further when I get home in an hour or two.

**Comment by amenadiel** [comment]
@sadortun please consider that a fair share of the userbase might be using semver in their composer.json

If the version is specified as in mine (^0.0.1) it's meant to accept non breaking changes. 

Releasing 1.0 when there aren't breaking changes  is misleading and breaks the meaning of semantic versioning.

**Comment by sadortun** [comment]
Good point! @amenadiel

**Comment by sadortun** [comment]
@djlambert Indeed,  missing the GeomFromText()
DQL >  SELECT p FROM CrEOF\Spatial\Tests\Fixtures\PolygonEntity p WHERE Contains(p.polygon,  new Point(6,6) ) = 1

SQL > SELECT p0_.id AS id0, AsBinary(p0_.polygon) AS polygon1 FROM PolygonEntity p0_ WHERE Contains(p0_.polygon, 'POINT(6 6)')

**Comment by djlambert** [comment]
@sadortun was about to respond with the same regarding 0.y.z, your entire comment didn't show up in email.

I agree complete, particularly so since the library is being used in production. This also, https://packagist.org/packages/creof/doctrine2-spatial/dependents.

This also resolves the query parameter handling question. Adding the GeomFromText/ST_GeomFromText to DQL with orm < 2.5.1 would break existing code, as demonstrated by the tests prior to afa413b27cab65ec58e1cc456dfe374862ee0cc9. I'll fix the tests.

**Comment by sadortun** [comment]
Looking at the diff, I guess that if you had GeomFromText() && orm > 2.5.1 it would break your queries?

To work in all 'orm' you could do something like : ( it's just an idea, probably a bad idea .... )
'''Sql
SELECT p
                                    FROM PolyEntry p
                                    INNER JOIN PointEntry t
                                          WITH Contains(p.poly,t.poly) = 1 
                                    WHERE t.id = :id
'''

Or add  'OrmTest::MaybeWhereGeomFromText() that would print either '?' Or 'GeomFromText(?)'

Anyway, we need to make clear that there is new stuff going on in 'orm' > 2.5

**Comment by djlambert** [comment]
I just pushed test changes to my fork 93ce45b9ccddad925e179ba672538b7aff361039. They are all passing locally now, let's see what Travis has to say.

Let people continue to wrap DQL parameters for orm < 2.5.1, and a note in the readme they'll need t review their DQL for >= 2.5.1?

**Comment by djlambert** [comment]
Submitted #95

**Comment by djlambert** [comment]
Submitted #98 as alternative to #95.

**Comment by sadortun** [comment]
Great! We will have to add a few tests to cover the  behaviour of <2.5.1 and >= 2.5.1

**Comment by djlambert** [comment]
I just added a tag for 1.0.0. Should that have been 1.0? The symver site isn't very clear on that point.

**Comment by sadortun** [comment]
The Z in X.Y.Z, is ususaly for "patch" level releases, it can be a good idea to have it.

X =  backward incompatible changes
Y =  New features
Z = Bug fixes

**Comment by ddproxy** [comment]
Agreed x.y.z, I meant to get docs in order by now but I've been busy tackling redis queuing. I'll see what I can whip up for either a patch or minor update.
